apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: logs-dashboard
  labels:
    app.kubernetes.io/name: logs-dashboard-db
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # Uncomment and set your storage class if needed
  # storageClassName: standard
